### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dmzone** [davidhellmann/generator-baukasten#6]
**********
yo -v: 2.0.0
npm -v: 5.0.4
W10
**********

D:\xampp\htdocs\***>yo baukasten

C:\Users\***\AppData\Roaming\npm\node_modules\generator-baukasten\generators\app\index.js:71
    async initializing() {
          ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as baukasten:app] (C:\Users\***\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:38:27)
    at Store.get (C:\Users\***\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:61:39)

**Comment by davidhellmann** [comment]
hm. some more informations please :)

**Comment by terryoy** [comment]
I can reproduce this bug on macOS Sierra

Node: v6.10.0
npm: 3.10.10
yo: 2.0.0

```bash
$ mkdir baukasten && cd baukasten
$ npm install generator-baukasten
$ yo baukasten

/Users/terryoy/work/projects/frontend-toolchain/baukasten/node_modules/generator-baukasten/generators/app/index.js:71
    async initializing() {
          ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as baukasten:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:61:39)
```

**Comment by artoric** [comment]
Same issue here:

```/Users/lk/Projects/frame-baukasten/node_modules/generator-baukasten/generators/app/index.js:71
    async initializing() {
          ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as baukasten:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
```

I would really like to test your Baukasten: I'm using dhBoilerplate daily and I'm sure Baukasten rocks!
Vielen Dank, David!

**Comment by artoric** [comment]
@terryoy Upgrade your node.js to the latest (not stable):
```
sudo npm install n -g
sudo n latest
```
Node supports async/await from version 7.6. -@davidhellmann, maybe could you mention this in the Readme file,...
