### ISSUE TITLE
Bauskasten unter Windows nutzen

### ISSUE THREAD

**Issue by KrasserTommy** [davidhellmann/generator-baukasten#63]
Ist es möglich den Baukasten auch auf Windows zu nutzen? Kämpfe mich gerade durch den Generator. Zuerst musste ich mit den Windows Build Tools klar kommen, nachdem das Problem beseitigt wurde, kommen nun Probleme mit dem "Sh" Befehl.

Gibt es schon Erfahrungen unter Windows?

**Comment by davidhellmann** [comment]
@KrasserTommy hey,
sorry. Support ist eher eingestellt. 
Unter Windows kann ich aber auch gar keine Erfahrungen teilen. 
Ich habe ein WordPress Projekt am Mac laufen damit und das geht ohne Probleme. 

Was sind denn die Fehlermeldungen?

**Comment by KrasserTommy** [comment]
Hey David, danke für die Antwort. Schade, der Baukasten sieht wirklich gut aus. Benutzt du mittlerweile einen anderen Weg?
Unter Widowns ist der Sh Befehl nicht bekannt. Habe es jetzt auf meinem Mac ausprobiert. Nach ein paar Anpassungen der Node Version etc. funktioniert es wenigstens bis Setup database. 
Dann kommen folgende Fehler:
```
  [--- Setup Database ---]

yarn run v1.21.1
$ cd scripts && sh ./setup-db.sh
mysql: [Warning] Using a password on the command line interface can be insecure.
./setup-db.sh: line 3: ../___src/_imports/craft3.sql.gz: No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
✨  Done in 0.23s.

  [--- Install Plugins ---]

yarn run v1.21.1
$ cd ___dist && sh ./plugins.sh
sh: ./plugins.sh: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


  Init Project
  ·······························································································

yarn run v1.21.1
$ cross-env NODE_ENV=production gulp init && npm run webpack && cd ___dist && composer install
[21:52:33] Requiring external module @babel/register

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

[21:52:36] Using gulpfile ~/Desktop/testwp/gulpfile.babel.js
[21:52:36] Starting 'init'...
[21:52:36] Starting 'compile:templates'...
[21:52:36] Starting 'copy:systemFiles'...
[21:52:36] Starting 'copy:fonts'...
[21:52:36] Starting 'create:inlineJS'...
[21:52:36] Starting 'copy:svg-single'...
[21:52:36] Starting 'create:svg-sprite'...
[21:52:37] Finished 'copy:fonts' after 618 ms
[21:52:37] Finished 'copy:systemFiles' after 1.13 s
[21:52:37] Finished 'create:inlineJS' after 1.14 s
[21:52:38] gulp-imagemin: Minified 1 image (saved 455 B - 35.9%)
[21:52:39] gulp-imagemin: Minified 81 images (saved 111 kB - 55%)
[21:52:39] all files 92.05 kB
[21:52:39] Finished 'copy:svg-single' after 2.44 s
[21:52:39] Finished 'compile:templates' after 2.44 s
[21:52:39] all files 159.59 kB
[21:52:39] Finished 'create:svg-sprite' after 2.49 s
[21:52:39] Finished 'init' after 2.49 s
npm WARN lifecycle The node binary used for scripts is /var/folders/hj/fd28v45544xbwgxzpnbqt7dr0000gn/T/yarn--1583527952964-0.155424245434312/node but npm is using ******.nvm/versions/node/v12.16.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> testProject@0.0.1 webpack ******/testwp
> cross-env NODE_ENV=production webpack --hide-modules --mode=production --config=webpack/webpack.config.babel.js


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3



 ERROR  Failed to compile with 9 errors                                                                                                     21:52:48

These relative modules were not found:

* ../../../templates/_atoms/codeSnippet/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_atoms/input/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_atoms/textarea/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_molecules/gridOverlay/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_molecules/vueComp/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_organisms/accordion/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_organisms/cards/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_organisms/imageGallery/_script in ./___src/assets/js/partials/modules.js
* ../../../templates/_organisms/imageSlider/_script in ./___src/assets/js/partials/modules.js
Hash: 42bf87bfb5e57076e58f
Version: webpack 4.42.0
Time: 6977ms
Built at: 2020-03-06 21:52:48
 4 assets
Entrypoint app = js/vendors~app.076919a5db359c55a0d3.js js/vendors~app.076919a5db359c55a0d3.js.map js/app.42bf87bfb5e57076e58f.min.js js/app.42bf87bfb5e57076e58f.min.js.map

ERROR in ./___src/assets/js/partials/modules.js
Module Error (from ./node_modules/eslint-loader/index.js):

******/testwp/___src/assets/js/partials/modules.js
   6:25  error  Missing file extension for "../../../templates/_atoms/codeSnippet/_script"       import/extensions
   7:25  error  Missing file extension for "../../../templates/_organisms/imageSlider/_script"   import/extensions
   8:26  error  Missing file extension for "../../../templates/_organisms/imageGallery/_script"  import/extensions
   9:19  error  Missing file extension for "../../../templates/_atoms/input/_script"             import/extensions
  10:22  error  Missing file extension for "../../../templates/_atoms/textarea/_script"          import/extensions
  11:26  error  Missing file extension for "../../../templates/_organisms/accordion/_script"     import/extensions
  12:28  error  Missing file extension for "../../../templates/_molecules/gridOverlay/_script"   import/extensions
  13:24  error  Missing file extension for "../../../templates/_molecules/vueComp/_script"       import/extensions
  14:19  error  Missing file extension for "../../../templates/_organisms/cards/_script"         import/extensions

✖ 9 problems (9 errors, 0 warnings)

 @ ./___src/assets/js/app.js 16:0-41 21:4-11

ERROR in ./___src/assets/css/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '../../templates/_embeds/home/style';
^
      File to import not found or unreadable: ../../templates/_embeds/home/style.
      in ******/testwp/___src/assets/css/_modules.scss (line 8, column 1)
    at ******/testwp/node_modules/webpack/lib/NormalModule.js:316:20
    at ******/testwp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at ******/testwp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (******/testwp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (******/testwp/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (******/testwp/node_modules/neo-async/async.js:8067:18)
    at options.error (******/testwp/node_modules/node-sass/lib/index.js:294:32)
 @ ./___src/assets/js/app.js 11:0-25

ERROR in ./___src/assets/css/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '../../templates/_embeds/home/style';
^
      File to import not found or unreadable: ../../templates/_embeds/home/style.
      in ******/testwp/___src/assets/css/_modules.scss (line 8, column 1)
    at ******/testwp/node_modules/webpack/lib/NormalModule.js:316:20
    at ******/testwp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at ******/testwp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (******/testwp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (******/testwp/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (******/testwp/node_modules/neo-async/async.js:8067:18)
    at options.error (******/testwp/node_modules/node-sass/lib/index.js:294:32)
 @ ./___src/assets/css/app.scss

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_atoms/codeSnippet/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 5:0-72 20:0-11
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_atoms/input/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 8:0-60 20:40-45
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_atoms/textarea/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 9:0-66 20:47-55
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_molecules/gridOverlay/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 11:0-76 20:68-79
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_molecules/vueComp/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 12:0-68 20:81-88
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_organisms/accordion/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 10:0-72 20:57-66
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_organisms/cards/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 13:0-64 20:90-95
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_organisms/imageGallery/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 7:0-78 20:26-38
 @ ./___src/assets/js/app.js

ERROR in ./___src/assets/js/partials/modules.js
Module not found: Error: Can't resolve '../../../templates/_organisms/imageSlider/_script' in '******/testwp/___src/assets/js/partials'
 @ ./___src/assets/js/partials/modules.js 6:0-76 20:13-24
 @ ./___src/assets/js/app.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--7-2!node_modules/postcss-loader/lib/index.js??ref--7-3!node_modules/sass-loader/lib/loader.js??ref--7-4!node_modules/sass-resources-loader/lib/loader.js??ref--7-5!___src/assets/css/app.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    
    ERROR in ./___src/assets/css/app.scss (./node_modules/css-loader??ref--7-2!./node_modules/postcss-loader/lib??ref--7-3!./node_modules/sass-loader/lib/loader.js??ref--7-4!./node_modules/sass-resources-loader/lib/loader.js??ref--7-5!./___src/assets/css/app.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    
    @import '../../templates/_embeds/home/style';
    ^
          File to import not found or unreadable: ../../templates/_embeds/home/style.
          in ******/testwp/___src/assets/css/_modules.scss (line 8, column 1)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--7-2!node_modules/postcss-loader/lib/index.js??ref--7-3!node_modules/sass-loader/lib/loader.js??ref--7-4!node_modules/sass-resources-loader/lib/loader.js??ref--7-5!___src/assets/css/app.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    
    ERROR in ./___src/assets/css/app.scss (./node_modules/css-loader??ref--7-2!./node_modules/postcss-loader/lib??ref--7-3!./node_modules/sass-loader/lib/loader.js??ref--7-4!./node_modules/sass-resources-loader/lib/loader.js??ref--7-5!./___src/assets/css/app.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    
    @import '../../templates/_embeds/home/style';
    ^
          File to import not found or unreadable: ../../templates/_embeds/home/style.
          in ******/testwp/___src/assets/css/_modules.scss (line 8, column 1)
Child html-webpack-plugin for "../wp-content/themes/testProject/_partials/_webpack/_webpack-header.php":
     1 asset
    Entrypoint undefined = ../wp-content/themes/testProject/_partials/_webpack/_webpack-header.php
Child html-webpack-plugin for "../wp-content/themes/testProject/_partials/_webpack/_webpack-scripts.php":
     1 asset
    Entrypoint undefined = ../wp-content/themes/testProject/_partials/_webpack/_webpack-scripts.php
Webpack Bundle Analyzer saved stats file to ******/testwp/webpack/stats.json
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! testProject@0.0.1 webpack: `cross-env NODE_ENV=production webpack --hide-modules --mode=production --config=webpack/webpack.config.babel.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the testProject@0.0.1 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ******.npm/_logs/2020-03-06T20_52_49_655Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by davidhellmann** [comment]
Ich mach aktuell kein WordPress mehr. Deswegen wird das hier auch nicht mehr wirklich supported. 
Und Windows werd ich leider eh nicht helfen können :(

Tut mit leid!
