### ISSUE TITLE
Gutil is not defined

### ISSUE THREAD

**Issue by gisu** [davidhellmann/generator-baukasten#9]
Installtree - Craft2 

```
[23:46:34] ReferenceError: gutil is not defined
    at Gulp.copyFonts (/Users/gisu/Development/private/baukasten/gulp/tasks/fontsCopy.js:10:70)
    at module.exports (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/gisu/Development/private/baukasten/node_modules/run-sequence/index.js:86:16)
    at runSequence (/Users/gisu/Development/private/baukasten/node_modules/run-sequence/index.js:97:2)
    at Gulp.initTask (/Users/gisu/Development/private/baukasten/gulp/tasks/init.js:5:5)
    at module.exports (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/gisu/Development/private/baukasten/node_modules/orchestrator/index.js:134:8)
    at /Users/gisu/Development/private/baukasten/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by davidhellmann** [comment]
Pushed an update.
